### ISSUE TITLE
Get error 'init.lua:298: Failed to unload buffer' when post summary description for MR

### ISSUE THREAD

**Issue by sergey-arkhipov** [harrisoncramer/gitlab.nvim#308] opened 2024-06-03 14:43 UTC
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

Default configuration

## Bug Description

When post summary for MR get error

```bash
Error detected while processing BufWinLeave Autocommands for "<buffer=5>":
E937: Attempt to delete a buffer that is in use: [No Name]
Error executing lua callback: ...s/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:298: Failed to unload buffer.
stack traceback:
  [C]: in function 'nvim_buf_delete'
  ...s/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:298: in function '_buf_destroy'
  ...s/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:322: in function 'unmount'
  .../.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/state.lua:270: in function 'exit'
  .../.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/state.lua:319: in function <.../.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/state.lua:312>
  [C]: in function 'nvim_buf_delete'
  .../.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/state.lua:293: in function <.../.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/state.lua:289>

```

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Add some description for MR
4. POST (save)

## Screenshots

![Screenshot 2024-06-03 at 17 42 33](https://github.com/harrisoncramer/gitlab.nvim/assets/5460458/fcd6d84e-8124-42b4-8d6a-a6c5ef14f03d)

**Comment by harrisoncramer** [comment] 2024-06-11 12:20
Just to be clear, is this when adding a description to an existing MR, or is this creating a new MR? 

And when you say `POST (save)` what specific action are you taking -- are you doing a primary action with the MR description open, in order to save and send to Gitlab? I'm not able to replicate this so any more detail you can provide will be helpful.

**Comment by sergey-arkhipov** [comment] 2024-06-11 18:10
> any more detail you can provide will be helpful

With peasure,

Simple steps.

1. git checkout to existed MR
2. run nvim
3. Open summary windows, in my keybinding - <leader> g(gitlab) -s (summary)
4. Add|modify something
5. Save your work (it's was called POST in previous description). Pressed <Leader>s in my current keybinging.
6. Get two message 
One - notice - Summary updated
Second - error (see screenshot with error)

P.S. I can reproduce this error after update to 2.6.3
```

  ● gitlab.nvim 62.68ms  start
                         dir     /Users/as/.local/share/nvim/lazy/gitlab.nvim
                         url     https://github.com/harrisoncramer/gitlab.nvim
                         version 2.6.3
                         tag     v2.6.3
                         branch  main
                         commit  96d7e16
                         readme  README.md
                         help    |gitlab.nvim.txt|

```

**Comment by harrisoncramer** [comment] 2024-06-17 01:07
Hello,

Thank you for filing such a comprehensive report. Unfortunately, I'm not able to replicate this issue following your steps.

The error seems to be coming during the `exit` function, which we use to clean up popups that are rendered to show you information, such as the summary text, branch name, and so forth. If you'd like to debug further you could look into that function specifically, the problem is the `popup:unmount()` function call which is called as part of a `BufWinLeave` 

It seems for you, not sure why, but that function is firing to "clean up" (e.g. unmount) a buffer that's also in use?

**Comment by jakubbortlik** [comment] 2024-06-17 04:19
Hi, I've noticed one detail that might be significant: The buffer name in the error is `[No Name]`. However, I believe all the buffers created by the `gitlab.summary` action are named `[Scratch]` - when I open `nvim` and run `gitlab.summary`, the only buffer that is marked as `[No Name]` (run `:ls!` with a `!` because the summary buffers are unlisted) is the empty buffer that `nvim` created on startup. It looks like for some reason `nvim` is trying to also close that buffer.

@sergey-arkhipov do you use `<leader>s` simply as the keymap for `settings.popup.perform_action` or do you have some more complicated mapping in place? Could you please provide a minimal init with which you can reproduce the error? You can use this lazy-based init for inspiration:
```lua
-- This is a minimal init.lua that is used for debugging
local root = vim.fn.stdpath("run") .. "/nvim/mininit"
vim.fn.mkdir(root, "p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "harrisoncramer/gitlab.nvim",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "sindrets/diffview.nvim",
      "stevearc/dressing.nvim",
    },
    config = function()
      local gitlab = require("gitlab")
      gitlab.setup()
      vim.keymap.set("n", "gls", gitlab.summary, {desc = "Gitlab Summary"})
    end
  }
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by sergey-arkhipov** [comment] 2024-06-17 08:24
@jakubbortlik ,thank you for the clarification.

Found the reason, I am using [alpha-nvim](https://github.com/goolord/alpha-nvim) and there is no empty buffer on startup, only scratch
```
 1u%a- "[Scratch]" line 18.
 13u a- "[Scratch]" line 0
 14u a- "[Scratch]" line 0
```
Similar problem when using [dashboard-nvim](https://github.com/nvimdev/dashboard-nvim)

The problem can be circumvented by creating an empty buffer after starting nvim - then there will be no error.

I assume the compatibility issue is not gitlab.nvim related, but if there is a way to check for an empty buffer, that would be great.

**Comment by jakubbortlik** [comment] 2024-06-19 07:56
@sergey-arkhipov, can you please try out the branch in #315 to see, whether it fixes your issue?

**Comment by sergey-arkhipov** [comment] 2024-06-20 09:04
> @sergey-arkhipov, can you please try out the branch in #315 to see, whether it fixes your issue?

I can confirm that the error has disappeared.
Thank you very much for solving the problem

**Comment by harrisoncramer** [comment] 2024-06-26 14:30
This is now in main. Thanks all, closing!

**Closed by harrisoncramer** 2024-06-26 14:30 UTC
Labels: bug, cannot replicate
