### ISSUE TITLE
Namespaced ID Not Building Correctly

### ISSUE THREAD

**Issue by proivk** [harrisoncramer/gitlab.nvim#77] opened 2023-11-01 09:06 UTC
## Feature Description
```
This plugin requires a .gitlab.nvim file in the root of the project. Provide this file with values required to connect to your gitlab instance of your repository (gitlab_url is optional, use ONLY for self-hosted instances):
```
Get all required information about project automatically w/o creating of .gitlab.nvim file in the root of cloned project.

1. Set auth token in env - prerequisite
2. Set self-hosted gitlab instance URL in env - prerequisite
3. Get current project name (something like that):  git remote get-url origin | xargs basename -s .git 
4. Get project id by project name: curl --header "Private-Token: <your_token>" -X GET https://gitlab.com/api/v4/projects?search=<project_name>

**Comment by johnybx** [comment] 2023-11-02 09:33
@harrisoncramer what do you think about that ? It looks like good idea and will also fix #76.

**Comment by harrisoncramer** [comment] 2023-11-06 23:43
Hey @proivk thank you very much for filing this issue, it's not a bad idea.

One issue is with having everything set in environment variables, is that some users have multiple Gitlab projects. Having a configuration file in each project is a very simple way to configure each project separately. Many Neovim users are closing and opening terminal sessions constantly, and juggling different environment variables (token and URL) between projects may be difficult. It also helps us understand very easily when we start up the Go server that a project is actually meant to be a Gitlab project (and not some other Git project).

Is the dot file causing friction for you in some way? I'm not necessarily opposed to doing something like this but would want to be careful about causing more problems than we currently have.

**Comment by proivk** [comment] 2023-11-07 08:27
Agree, but it is not necessarily to completely kick off the current approach.
If there is no such file in git repo, try to pick up all you need from env variables and/or automatically. 
.gitlab.nvim file should have priority over env configuration.
Having pre-defined configuration is useful for those who 99% of time works with one version of gitlab (my case, actually) - self-hosted or public (gitlab.com). Hybrid mode (env + .gitlab.nvim file) for those who uses both from time to time.

**Comment by harrisoncramer** [comment] 2023-11-07 18:38
Yeah that makes sense to me, and is what I was going to suggest trying (look for environment variables with a `.gitlab.nvim` file taking precedence). Do you want to take a crack at implementing this? 

If not I'll try to work on it shortly.

**Comment by harrisoncramer** [comment] 2023-11-09 03:53
Please try this branch and tell me if it works for you @proivk https://github.com/harrisoncramer/gitlab.nvim/pull/84

**Comment by harrisoncramer** [comment] 2023-11-18 00:08
Hey, so we aren't going to use a project ID number because that's not part of the Git project locally and we're trying to reduce the configuration overhead for users. Per the Gitlab documentation (and as you mention) we can _and are_ using a namespaced ID instead.

We use this directly like this:

```go
project, _, err := c.git.Projects.GetProject(g.projectPath(), &opt)
```

The `g.projectPath()` function is parsing the namespace and project name from the local repository, and `go-gitlab` handles the URL path escaping for us, and expects a string in the format of `namespace/projectName` exactly. 

My guess is that something about your namespacing is not being captured. If you have an unusual namespace setup, then it might not be captured by our Regex. This regex is tested, if you'd like to submit a PR you can adjust the Regex. It's tested by `git_test.go` currently.

**Comment by harrisoncramer** [comment] 2023-11-21 22:18
Can't reproduce, if there are issues w/ regex we can reopen this issue in the future.

**Closed by harrisoncramer** 2023-11-21 22:18 UTC
Labels: bug
