### ISSUE TITLE
Discussion List is not Updated after Delete

### ISSUE THREAD

**Issue by mnbroatch** [harrisoncramer/gitlab.nvim#28] opened 2023-08-15 00:48 UTC
**Describe the bug**
The discussion list does not update after deleting a comment.

**To Reproduce**
1. Make a comment
2. Open the discussion list
3. delete the comment

**Expected behavior**
I expect the deleted comment to disappear from the discussion list. However, unlike with adding replies or editing comments, the discussion list does not update to reflect that the comment has been deleted.

**Screenshots**

**Desktop (please complete the following information):**

**Comment by harrisoncramer** [comment] 2023-08-15 03:16
Should be fixed. Please let me know if not.

**Comment by mnbroatch** [comment] 2023-08-15 03:33
Hmm, now this is happening when I create a comment after opening and closing the discussion_list:

```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/gitlab.nvim/lua/gitlab/discussions.lua:184: BufWinEnter Autocommands for "<buffer=11>": Vim(append):Error executing lua callback: ...h
/.local/share/nvim/lazy/nui.nvim/lua/nui/split/init.lua:235: Invalid 'group': 'nui_5_hide'
stack traceback:
  [C]: in function 'create'
  ...h/.local/share/nvim/lazy/nui.nvim/lua/nui/split/init.lua:235: in function <...h/.local/share/nvim/lazy/nui.nvim/lua/nui/split/init.lua:234>
  [C]: in function 'nvim_buf_set_lines'
  ...l/share/nvim/lazy/gitlab.nvim/lua/gitlab/discussions.lua:184: in function 'callback'
  ...ch/.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/job.lua:25: in function ''
  vim/_editor.lua: in function ''
  vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
  [C]: in function 'nvim_buf_set_lines'
  ...l/share/nvim/lazy/gitlab.nvim/lua/gitlab/discussions.lua:184: in function 'callback'
  ...ch/.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/job.lua:25: in function ''
  vim/_editor.lua: in function ''
  vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by harrisoncramer** [comment] 2023-08-15 15:58
Yeah I'm probably not going to address that issue with the last comment. I'm aware of what's happening with the first issue and can try to address soon. Are you closing the buffer with `:bd` rather than `:q` perchance? I think the issue is that the buffer itself has been destroyed when we try to refresh the tree -- will take a look at this later tonight

**Comment by harrisoncramer** [comment] 2023-08-19 01:39
This should be fixed, was able to replicate and just merged in a fix @mnbroatch

**Closed** 2023-08-19 01:38 UTC
Labels: bug
