### ISSUE TITLE
Gitlab mr diff differs from that of glab

### ISSUE THREAD

**Issue by gunslingerfry** [harrisoncramer/gitlab.nvim#72] opened 2023-10-31 21:24 UTC
## Prerequsities

- [X] The "Troubleshooting" section of the README did not help
- [X] I've installed the required dependencies
- [X] I'm on the latest version of the plugin

## Bug Description

The gitlab.nvim plugin seems to be checking the local code against the main branch (ours is 'staging'). However, when the branch is out of date this introduces diff output that seem to be part of the merge request but are not. _I understand that commands like `git diff ..staging` have the same problem._

However, when using `glab mr diff` the diff output does not include commits to the main branch that are not merged/rebased into the current branch. It correctly shows just the changes introduced in the branch.

It may be impossible to do what glab is doing. But there is weirdness here in having to check out someone else's code and manually rebasing/merging things locally just to do a proper code review.

**Comment by harrisoncramer** [comment] 2023-10-31 21:41
This is a duplicate of https://github.com/harrisoncramer/gitlab.nvim/issues/63

I'm interested in fixing this but have not gotten to it yet.

**Closed by harrisoncramer** 2023-10-31 21:41 UTC
